"""phase 6 initial schema

Revision ID: cbb0182b0217
Revises:
Create Date: 2026-05-28 11:51:44.822508

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbb0182b0217"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trace",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("query_id", sa.String(length=36), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("context_truncated", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("retrieval_strategy", sa.String(length=32), nullable=False),
        sa.Column("top_k", sa.Integer(), nullable=False),
        sa.Column("chunks_retrieved", sa.Integer(), nullable=False),
        sa.Column("model_used", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_trace_created_at_desc", "trace", [sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index(op.f("ix_trace_query_id"), "trace", ["query_id"], unique=True)
    op.create_index(op.f("ix_trace_trace_id"), "trace", ["trace_id"], unique=False)
    op.create_table(
        "defect_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("query_id", sa.String(length=36), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("defect_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["query_id"], ["trace.query_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_defect_event_defect_type"), "defect_event", ["defect_type"], unique=False
    )
    op.create_index(op.f("ix_defect_event_query_id"), "defect_event", ["query_id"], unique=False)
    op.create_index(op.f("ix_defect_event_severity"), "defect_event", ["severity"], unique=False)
    op.create_index(op.f("ix_defect_event_trace_id"), "defect_event", ["trace_id"], unique=False)
    op.create_table(
        "eval_score",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("query_id", sa.String(length=36), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("faithfulness", sa.Float(), nullable=True),
        sa.Column("context_recall", sa.Float(), nullable=True),
        sa.Column("answer_relevancy", sa.Float(), nullable=True),
        sa.Column("quality_gate_result", sa.String(length=8), nullable=False),
        sa.Column("evaluation_latency_ms", sa.Integer(), nullable=False),
        sa.Column("judge_model", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["query_id"], ["trace.query_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eval_score_quality_gate_result"),
        "eval_score",
        ["quality_gate_result"],
        unique=False,
    )
    op.create_index(op.f("ix_eval_score_query_id"), "eval_score", ["query_id"], unique=False)
    op.create_index(op.f("ix_eval_score_trace_id"), "eval_score", ["trace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_eval_score_trace_id"), table_name="eval_score")
    op.drop_index(op.f("ix_eval_score_query_id"), table_name="eval_score")
    op.drop_index(op.f("ix_eval_score_quality_gate_result"), table_name="eval_score")
    op.drop_table("eval_score")
    op.drop_index(op.f("ix_defect_event_trace_id"), table_name="defect_event")
    op.drop_index(op.f("ix_defect_event_severity"), table_name="defect_event")
    op.drop_index(op.f("ix_defect_event_query_id"), table_name="defect_event")
    op.drop_index(op.f("ix_defect_event_defect_type"), table_name="defect_event")
    op.drop_table("defect_event")
    op.drop_index(op.f("ix_trace_trace_id"), table_name="trace")
    op.drop_index(op.f("ix_trace_query_id"), table_name="trace")
    op.drop_index("ix_trace_created_at_desc", table_name="trace")
    op.drop_table("trace")
    # ### end Alembic commands ###
